[package]
name = "mpv_websocket"
version = "0.1.0"
edition = "2021"

[features]
talk-tts = ["tts"]


[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
parity-tokio-ipc = "0.9.0"
serde = { version = "1.0.155", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.94", default-features = false, features = ["std"] }
tokio = { version = "1.26.0", default-features = false, features = ["macros", "rt-multi-thread", "io-util"] }
ws = { version = "0.9.2", default-features = false }
tts = { version = "0.25.6", optional = true }
